### ISSUE TITLE
Remove “Sign out” button in the app shelf

### ISSUE THREAD

**Issue by vnys** [equinor/chromebook#2]
There’s a big button with a light red background in the shelf (bottom row of app shortcuts) with the text “Sign out”. Why do we need a second sign out button to take up unnecessary space in the shelf when there”s already one in the taskbar? 

![Screenshot 2021-10-09 09 23 56](https://user-images.githubusercontent.com/2081882/136648612-47a40b89-b249-40e6-b1c8-78c91a9e18c9.png)

![image](https://user-images.githubusercontent.com/2081882/100211727-c7046880-2f0c-11eb-844d-8a38254e4df4.png)

**Comment by knu73r1k** [comment]
Tried to disable the "sign out" button in the shelf. Does not see any effects yet ..

**Comment by knu73r1k** [comment]
Edit : Works now .. "sign out" - disabled.
