### ISSUE TITLE
Disable sending diagnostics and usage data to Google

### ISSUE THREAD

**Issue by vnys** [equinor/chromebook#3]
In order to configure a Chromebook for maximum privacy, this option should be turned off – or at least be up to the user to decide if she wants enabled.

![Screenshot 2021-10-09 09 18 24](https://user-images.githubusercontent.com/2081882/136648515-d6ed596d-4426-4e6d-ae5a-dd2649fa7329.png)

**Comment by knu73r1k** [comment]
Fixed - on the "User and device reporting" pane in the admin console. - "Anonymous metric reporting" is now set to "Never send metrics to google".
